[project]
name = "pv2"
version = "0.9.1"
description = "PV2 backend framework module"
readme = "README.md"
authors = [
  { name = "Louis Abel", email = "label@rockylinux.org" }
]

maintainers = [
  { name = "Louis Abel", email = "label@rockylinux.org" }
]

requires-python = ">=3.6"

dependencies = [
  "GitPython >= 3.1.30",
  "lxml >= 4.6.5",
  "file-magic >= 0.4.0"
]

[project.urls]
"Homepage" = "https://github.com/peridotbuild/pv2"
"Bug Tracker" = "https://github.com/peridotbuild/pv2/issues"

[project.license]
file = "LICENSE"

[tool.setuptools]
package-dir = { "pv2" = "pv2" }
