[project]
name = "pv2"
version = "0.9.1"

authors = [
  "Louis Abel <label@rockylinux.org>"
]

maintainers = [
  "Louis Abel <label@rockylinux.org>"
]

description = "PV2 backend framework module"
readme = "README.md"
license = "MIT"
requires-python = ">=3.6"

dependencies = [
  "rpm >= 4.16.1",
  "GitPython >= 3.1.30",
  "lxml >= 4.6.5",
  "file-magic >= 0.4.0"
]

[project.urls]
"Homepage" = "https://github.com/peridotbuild/pv2"
"Bug Tracker" = "https://github.com/peridotbuild/pv2/issues"
